# Generated by Django 5.2.7 on 2025-10-16 06:09

import django.db.models.deletion
import workshops.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('institute', models.CharField(blank=True, max_length=255)),
                ('online_link', models.URLField(blank=True)),
                ('mode', models.CharField(choices=[('physical', 'Physical'), ('online', 'Online')], max_length=20)),
                ('coordinator_email', models.EmailField(max_length=254)),
                ('coordinator_phone', models.CharField(max_length=20)),
                ('registration_link', models.URLField(blank=True)),
                ('agenda_pdf', models.FileField(blank=True, null=True, upload_to='agendas/')),
                ('feedback_form_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('reports_approved', models.BooleanField(default=False)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinated_workshops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('feedback_summary', 'Feedback Summary'), ('attendance', 'Attendance Report'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to=workshops.models.workshop_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workshops.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=workshops.models.workshop_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='workshops.workshop')),
            ],
        ),
    ]
